/* Canonical content -> static assets. No dependencies, network, or runtime patches. */
const fs = require('node:fs');
const path = require('node:path');
const {createHash} = require('node:crypto');
const root = path.resolve(__dirname, '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, name), 'utf8'));
const {version, years} = read('site.config.json');
const chapters = read('content/chapters.json');
const references = read('content/references.json');
const legacy = read('content/legacy-demos.json');
const groups = chapters.map(c => read(`content/chapter${c.number}.json`));
const notes = groups.flat();
const {comparisons,navigation,index}=require('./discovery.cjs')(notes,chapters,read('content/comparisons.json'));
const sources = notes.flatMap(n => n.sources.map(s => `${s.year}-${s.q}`));
if (new Set(notes.map(n => n.id)).size !== notes.length) throw Error('Duplicate note ID');
if (new Set(sources).size !== sources.length) throw Error('Duplicate exam source');
for (const n of notes) {
  if (!chapters[n.chapter - 1]?.sections.some(s => s.id === n.section)) throw Error(`Invalid section: ${n.id}`);
  if (n.searchAliases && (!Array.isArray(n.searchAliases) || n.searchAliases.some(alias=>typeof alias!=='string'||!alias.trim()))) throw Error(`Invalid search aliases: ${n.id}`);
}
const generated = path.join(root, 'generated');
fs.mkdirSync(generated, {recursive: true});
const write = (name, content) => fs.writeFileSync(path.join(root, name), content);
const js = value => JSON.stringify(value).replace(/</g, '\\u003c');
const fingerprint = name => createHash('sha256').update(fs.readFileSync(path.join(root,name))).digest('hex').slice(0,12);
const asset = (name, css = false) => css
  ? `  <link rel="stylesheet" href="./${name}?v=${version}&h=${fingerprint(name)}">`
  : `  <script src="./${name}?v=${version}&h=${fingerprint(name)}"></script>`;
write('generated/search-index.json',JSON.stringify(index));
const labManifest=read('src/labs/manifest.json');
for (const [i, group] of groups.entries()) {
  const chapter = chapters[i];
  const labFiles=labManifest.chapters[chapter.number].files;
  const labAsset=`generated/labs-chapter${chapter.number}.js`;
  if(labFiles.length)write(labAsset,'// Generated from src/labs; edit the corresponding chapter source.\n'+[...labManifest.shared,...labFiles].map(file=>fs.readFileSync(path.join(root,file),'utf8')).join('\n'));
  else if(fs.existsSync(path.join(root,labAsset)))fs.unlinkSync(path.join(root,labAsset));
  const subset = object => Object.fromEntries(group.filter(n => object[n.id]).map(n => [n.id, object[n.id]]));
  write(`generated/chapter${chapter.number}.js`, `// Generated by scripts/build.cjs; edit content/*.json.\nwindow.NOTES=${js({version, chapters, notes:group, sourceCount:sources.length, years})};\nwindow.NOTE_REFERENCES=${js(subset(references))};\nwindow.NOTE_DEMOS=${js(subset(legacy))};\nwindow.NOTE_NAVIGATION=${js(subset(navigation))};\n`);
  const css = ['notes-2020.css','simulations.css','note-labs.css','notes-study.css','notes-core.css',...(chapter.number>=6?['notes-extended.css']:[]),'notes-choices.css','notes-learning.css'];
  const scripts = [`generated/chapter${chapter.number}.js`,'simulations.js','notes-choices.js','note-labs-runtime.js',...(labFiles.length ? [labAsset] : []),'notes-reading.js','notes-app.js'];
  const replacements = {number:chapter.number,title:chapter.title,styles:css.map(name=>asset(name,true)).join('\n'),scripts:scripts.map(name=>asset(name)).join('\n')};
  write(`chapter${chapter.number}.html`, fs.readFileSync(path.join(root,'templates/chapter.html'),'utf8').replace(/{{(\w+)}}/g, (_,key)=>replacements[key]));
}
write('generated/catalogue.js', `// Generated; edit content/*.json.\nwindow.NOTE_CATALOGUE=${js({version,comparisons,searchIndex:`./generated/search-index.json?v=${version}&h=${fingerprint('generated/search-index.json')}`,sourceCount:sources.length,noteCount:notes.length,chapters:chapters.map((c,i)=>({...c,noteCount:groups[i].length,sourceCount:groups[i].reduce((sum,n)=>sum+n.sources.length,0)}))})};\n`);
write('index.html', fs.readFileSync(path.join(root,'templates/index.html'),'utf8').replaceAll('{{version}}',String(version)).replace(/((?:src|href)="\.\/([^"?]+\.(?:js|css))\?v=\d+)/g,(_,attribute,name)=>`${attribute}&h=${fingerprint(name)}`));
console.log(`Built v${version}: ${notes.length} notes, ${sources.length} sources, ${chapters.length} chapters.`);
